author: "tensorknower69"
category: Web
copyright: "2021 tensorknower69"
github: "tensorknower69/nhentai"
license: MIT
maintainer: "tensorknower69 <62006583+tensorknower69@users.noreply.github.com>"
name: "nhentai"
synopsis: "Scrape/download nhentai galleries and JSONs"
version: 0.1.3.0

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - text
  - modern-uri
  - time
  - refined
  - tagsoup
  - scalpel-core
  - lens
  - split
  - errors
  - exceptions
  - scientific
  - aeson
  - template-haskell

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wno-tabs
    - -Wno-name-shadowing

executables:
  nhentai:
    main: NHentai/Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Wno-tabs
      - -Wno-orphans
      - -Wno-unused-matches
      - -Wno-name-shadowing
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - nhentai
      - streaming
      - bytestring
      - optparse-applicative
      - mtl
      - monad-logger
      - monad-control
      - streaming-concurrency
      - filepath
      - directory
      - http-client
      - http-client-tls
      - http-types

tests:
  nhentai-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -Wno-tabs
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - nhentai
      - scalpel
      - tasty-hunit
      - tasty
      - http-client
      - http-client-tls
